export const CHOOSE_CONTINENT = 'CHOOSE_CONTINENT';
export const RECIEVE_COUNTRIES = 'RECIEVE_COUNTRIES';

export const ITEMS_REQUESTED = "ITEMS_REQUESTED";
export const ITEMS_RECEIVED = "ITEMS_RECEIVED";
